// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dinoApi.Models;

namespace dinoApi.Migrations
{
    [DbContext(typeof(dinoApiContext))]
    [Migration("20191031184548_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dinoApi.Models.Dino", b =>
                {
                    b.Property<int>("DinoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AsKnownAs");

                    b.Property<string>("Diet");

                    b.Property<string>("Habitat");

                    b.Property<string>("Mood");

                    b.Property<string>("Name");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Strength");

                    b.Property<string>("Type");

                    b.Property<string>("Weakness");

                    b.HasKey("DinoId");

                    b.ToTable("Dinos");

                    b.HasData(
                        new
                        {
                            DinoId = 1,
                            AsKnownAs = "Sand Lizard",
                            Diet = "Herbivorous",
                            Habitat = "Dense marsh lands",
                            Mood = "Arrogant",
                            Name = "Ammosaurus",
                            PhotoPath = "wwwroot/uploads/Ammosaurus.jpg",
                            Strength = "Long arms, able to walk on two feet",
                            Type = "Sauropod",
                            Weakness = "Not able to walk on four legs so there are issues when running away"
                        },
                        new
                        {
                            DinoId = 2,
                            AsKnownAs = "Huayang lizard'",
                            Diet = "Herbivorous",
                            Habitat = "Forest, center island",
                            Mood = "Relaxed",
                            Name = "Huayangosaurus",
                            PhotoPath = "wwwroot/uploads/huayango.jpg",
                            Strength = "Spiky spine leading to a long thick tail with aspikes coming out.",
                            Type = "Armoured Dinosour",
                            Weakness = "Under side of the dinosour. If the dinosour gets knocked off balance he has no hope."
                        },
                        new
                        {
                            DinoId = 3,
                            AsKnownAs = "T-rex or Tyrant lizard",
                            Diet = "Carnivorous",
                            Habitat = "Outskirts of the Island",
                            Mood = "Consistantly raging",
                            Name = "Tyrannosaurus",
                            PhotoPath = "wwwroot/uploads/Tyrannosaurus.jpg",
                            Strength = "Strong legs, huge mouth with large sharp teeth",
                            Type = "Large theropod",
                            Weakness = "short arms, cant swim"
                        },
                        new
                        {
                            DinoId = 4,
                            AsKnownAs = "quick plunderer or Raptor",
                            Diet = "Carnivorous",
                            Habitat = "Grass Lands outskirt of the jungle",
                            Mood = "Strategic",
                            Name = "Velociraptor",
                            PhotoPath = "wwwroot/uploads/Velociraptor.jpg",
                            Strength = "Very smart and fast",
                            Type = "Small theropod",
                            Weakness = "Smaller in size"
                        },
                        new
                        {
                            DinoId = 5,
                            AsKnownAs = "terrible claw",
                            Diet = "Carnivorous, mainly feeds on plant eating dinos",
                            Habitat = "Grass lands and jungle",
                            Mood = "mystical",
                            Name = "Deinonychus",
                            PhotoPath = "wwwroot/uploads/Deinonychus.jpg",
                            Strength = "Huge claws, moved swiftly",
                            Type = "Small theropod",
                            Weakness = "smaller in size"
                        },
                        new
                        {
                            DinoId = 6,
                            AsKnownAs = "Triciratops, bull lizard",
                            Diet = "Herbivorous",
                            Habitat = "Mountain basin",
                            Mood = "Gentel",
                            Name = "Torosaurus",
                            PhotoPath = "wwwroot/uploads/Torosaurus.jpg",
                            Strength = "Large strong crown with two large horns. Thick skin",
                            Type = "Ceratopsian",
                            Weakness = "Slow movement"
                        },
                        new
                        {
                            DinoId = 7,
                            AsKnownAs = "brave monitor lizard",
                            Diet = "herbivorous",
                            Habitat = "Beach side",
                            Mood = "Wise and aware",
                            Name = "brave monitor lizard",
                            PhotoPath = "wwwroot/uploads/Ouranosaurus.jpg",
                            Strength = "Strong swimmer, great eye site, sense of smell and hearing",
                            Type = "euornithopod",
                            Weakness = "weak body armour and no real type of defense"
                        },
                        new
                        {
                            DinoId = 8,
                            AsKnownAs = "Alamo lizard or Longnecks",
                            Diet = "Herbivorous",
                            Habitat = "Swamp Land",
                            Mood = "Wise and Chill",
                            Name = "Alamosaurus",
                            PhotoPath = "wwwroot/uploads/Alamosaurus.jpg",
                            Strength = "Long limbs, hard to take down. Over 20 meters in length",
                            Type = "Sauropod",
                            Weakness = "slwow moving dinosour"
                        },
                        new
                        {
                            DinoId = 9,
                            AsKnownAs = "Bambi plunderer",
                            Diet = "Carnivorous",
                            Habitat = "Jumgle",
                            Mood = "Mischievous",
                            Name = "Bambiraptor",
                            PhotoPath = "wwwroot/uploads/Bambiraptor.jpg",
                            Strength = "Extremly fast, large claws and capable of flying",
                            Type = "small theropod",
                            Weakness = "Very small, only 1 meter in length"
                        },
                        new
                        {
                            DinoId = 10,
                            AsKnownAs = "Good mother lizard",
                            Diet = "Herbivorous",
                            Habitat = "Mountain vally",
                            Mood = "Very protective",
                            Name = "Maiasaura",
                            PhotoPath = "wwwroot/uploads/Maiasaura.jpg",
                            Strength = "Very aware of their surroundings",
                            Type = "euornithopod",
                            Weakness = "no body armour or type of defense"
                        },
                        new
                        {
                            DinoId = 11,
                            AsKnownAs = "fleet lizard'",
                            Diet = "Carnivorous",
                            Habitat = "Plateau",
                            Mood = "Whitty",
                            Name = "Elaphrosaurus",
                            PhotoPath = "wwwroot/uploads/Elaphrosaurus.jpg",
                            Strength = "Tall long limbs, quick moving",
                            Type = "large theropod",
                            Weakness = "Not very strong"
                        },
                        new
                        {
                            DinoId = 12,
                            AsKnownAs = "Earth Lizard",
                            Diet = "Carnivorous",
                            Habitat = "Valley",
                            Mood = "Timmid",
                            Name = "Mapusaurus",
                            PhotoPath = "wwwroot/uploads/Mapusaurus.jpg",
                            Strength = "Large mouth and fast",
                            Type = "large theropod",
                            Weakness = "Slightly smaller that other preditors. Not as powerful"
                        },
                        new
                        {
                            DinoId = 13,
                            AsKnownAs = "Egg Thief",
                            Diet = "Omnivourous",
                            Habitat = "Dense Marsh Land",
                            Mood = "Mischievous",
                            Name = "Oviraptor",
                            PhotoPath = "wwwroot/uploads/Oviraptor.jpg",
                            Strength = "Keen sense of smell and very sneaky",
                            Type = "small theropod",
                            Weakness = "No real kind of defense"
                        },
                        new
                        {
                            DinoId = 14,
                            AsKnownAs = " Compso",
                            Diet = "Carnivorous",
                            Habitat = "Jumgle",
                            Mood = "Mischievous",
                            Name = "Procompsognathus",
                            PhotoPath = "wwwroot/uploads/Procompsognathus.jpg",
                            Strength = "Fast and sneaky",
                            Type = "Small Theropod",
                            Weakness = "timy in size, not dangerous alone"
                        },
                        new
                        {
                            DinoId = 15,
                            AsKnownAs = "king of the lizard eaters'",
                            Diet = "Carnivorous",
                            Habitat = "Mountain Valley",
                            Mood = "Independant jerk bird",
                            Name = "Saurophaganax",
                            PhotoPath = "wwwroot/uploads/Saurophaganax.jpg",
                            Strength = "All around strong",
                            Type = "Large theropod",
                            Weakness = "None"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
